fix: `cargo publish` command failed in last release due to dirty directory (#240)
Fix error caused by uncommited file:
```
    Updating crates.io index
    Updating crates.io index
error: 1 files in the working directory contain changes that were not yet committed into git:
this-release-notes.md
to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
```

Reviewed-on: https://codeberg.org/testtrim/testtrim/pulls/240
Co-authored-by: Mathieu Fenniak <mathieu@fenniak.net>
Co-committed-by: Mathieu Fenniak <mathieu@fenniak.net>